version: "3.7"
services:
  app:
    container_name: hs_api
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "laravel"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - cache
  db:
    container_name: hs_db
    image: mysql:5.7
    restart: always
    command: --sql_mode=""
    environment:
      MYSQL_DATABASE: hs
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
  cache:
    container_name: hs_redis
    image: redis:4-alpine
    restart: always
    volumes:
    - ./cache:/data 

volumes:
  app:
    driver: "local"
  cache:
    driver: "local"
  db:
    driver: "local"